In [310]:
import numpy as np

In [637]:
class SOM(object):
    
    def __init__(self, x, y, v_dim, i_aprendizaje, radio, epocas):
            
            
        #Inisializando Propiedades
        self._x = x
        self._y = y
        self.i_aprendizaje = float(i_aprendizaje)
        self._radio = float(radio)
        self._epocas = epocas
       
        
        for i in range(x):
            for j in range(y):
                self._iterador = np.array([i, j])
                
        
                
         
    def entrenar(self,datos):
        index_map =np.array(list(self._iterador))
        m_pesos = np.random.random((x*y,v_dim))
        for epoca_actual in range(self._epocas):
            #print(m_pesos)
            print (index_map)
            for v_entrada in datos:
                m_entrada=np.stack([v_entrada for i in range(x*y)])
                #print(m_entrada)
                raiz_distancias=np.sum(np.power(np.subtract(m_pesos, m_entrada),2),1)
                #print(raiz_distancias)
                bmu = np.argmin(raiz_distancias, 0)
                #print(bmu)
                bmu_loc=np.reshape(index_map[bmu],2)
                #print(bmu_loc)
                decay_function = np.subtract(1.0, np.divide(epoca_actual, self._epocas))
                #print(decay_function)
                aprendizaje_actual = np.multiply(i_aprendizaje, decay_function)
                #print(aprendizaje_actual)
                radio_actual = np.multiply(radio, decay_function)
                bmu_matriz = np.stack([bmu_loc for i in range(x*y)])
                #print(bmu_matriz)
                bmu_distance = np.sum(np.power(np.subtract(index_map, bmu_matriz), 2), 1)
                #print(bmu_distance)
                func_vecindad =np.exp(np.negative(np.divide(np.array(bmu_distance, dtype= np.float32), np.array(np.power(radio,2),dtype = np.float32))))
                #print(func_vecindad)
                matriz_aprendizaje = np.multiply(aprendizaje_actual, func_vecindad)
                #print(matriz_aprendizaje)
                multiplicador=np.stack([np.tile(matriz_aprendizaje[j],v_dim)for i in range(x*y)])
                delta = np.multiply(multiplicador,np.subtract(np.stack([v_entrada for i in range(x*y)]), m_pesos))   
                #print (delta)
                new_pesos = np.add(m_pesos, delta)
                m_pesos= new_pesos
                #print(m_pesos)
                
        centroid_matrix = [[] for i in range(x)]
        for i, loc in enumerate(index_map):
            centroid_matrix[loc[0]].append(new_pesos[i])
        #print(centroid_matrix)
                
                
    

In [638]:
datos = [[2, 3, 1, 1, 3, 3, 3, 3], 
         [3, 2, 1, 0, 3, 3, 3, 3], 
         [2, 3, 1, 1, 2, 3, 3, 3],
         [2, 3, 1, 1, 2, 2, 3, 3],
         [2, 3, 1, 1, 1, 2, 3, 3],
         [1, 3, 1, 1, 2, 2, 3, 3], 
         [2, 1, 0, 0, 2, 2, 3, 3],
         [2, 1, 0, 0, 3, 2, 3, 3], 
         [1, 1, 0, 0, 2, 1, 3, 3], 
         [1, 1, 0, 0, 2, 1, 3, 3], 
         [1, 1, 0, 0, 1, 1, 3, 3],
         [1, 1, 0, 0, 0, 0, 3, 3], 
         [1, 1, 0, 0, 1, 1, 3, 3], 
         [3, 3, 1, 1, 4, 4, 2, 3], 
         [3, 3, 1, 1, 4, 4, 2, 3], 
         [3, 3, 1, 1, 4, 4, 3, 2], 
         [3, 3, 1, 1, 4, 4, 1, 2], 
         [3, 3, 1, 1, 3, 3, 1, 2], 
         [3, 3, 1, 1, 4, 4, 1, 2], 
         [3, 3, 1, 1, 3, 3, 1, 2], 
         [3, 3, 1, 1, 4, 3, 1, 2], 
         [3, 2, 1, 1, 3, 3, 1, 2], 
         [3, 3, 1, 1, 3, 2, 1, 1], 
         [3, 3, 1, 1, 3, 2, 1, 1], 
         [3, 2, 1, 1, 3, 4, 1, 1], 
         [3, 2, 1, 1, 3, 4, 1, 1], 
         [3, 2, 1, 1, 3, 3, 2, 2], 
         [2, 1, 1, 1, 4, 4, 1, 1], 
         [0, 4, 1, 0, 3, 3, 3, 3], 
         [0, 4, 1, 0, 3, 3, 3, 3], 
         [0, 4, 0, 0, 3, 3, 3, 3], 
         [0, 4, 0, 0, 3, 3, 3, 3]]

In [640]:
som = SOM(3, 3,8, 0.5,  1.0, 1)
som.entrenar(datos)

[2 2]


IndexError: index 2 is out of bounds for axis 0 with size 2

###    inicializando los pesos

In [641]:
x=2
y=2
v_entrada = [2, 3, 1, 1, 3, 3, 3, 3]
i_aprendizaje = 0.5
epoca_actual = 15
epocas = 100
radio_actual = 0.5
radio = 1
v_dim=8
#-------
m_pesos = np.random.random((x*y,v_dim))
print (m_pesos)
#creando el mapa de indices 
index_map =np.array(list(_iterador(x, y)))
def _iterador(x,y):
        for i in range(x):
            for j in range(y):
                yield np.array([i, j])

print (index_map)

#matriz de entrada
m_entrada=np.stack([v_entrada for i in range(x*y)])
print (m_entrada)
bmu_loc=np.reshape(index_map[bmu],2)
print(bmu_loc)



[[0.612578   0.9787935  0.2935962  0.87775127 0.11243572 0.66795377
  0.09885203 0.56814859]
 [0.5844707  0.35573017 0.98999579 0.38113745 0.85929435 0.59659464
  0.18528063 0.63027487]
 [0.20829941 0.23794894 0.25268309 0.27589574 0.57508473 0.32795594
  0.12346985 0.34934343]
 [0.45299306 0.43791751 0.01828247 0.51825534 0.50266042 0.84720499
  0.65406402 0.8199012 ]]
[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[[2 3 1 1 3 3 3 3]
 [2 3 1 1 3 3 3 3]
 [2 3 1 1 3 3 3 3]
 [2 3 1 1 3 3 3 3]]
[1 0]


### Calcular distancias

In [313]:
raiz_distancias=np.sum(np.power(np.subtract(m_pesos, m_entrada),2),1)
print(raiz_distancias)


[37.68967162 31.54540132 30.83053993 36.33900193 33.38790428 36.41565483
 30.93068351 31.5311554  31.81003094]


###  indice de la neurona ganadora

In [314]:
bmu = np.argmin(raiz_distancias, 0)
#print (bmu)
#mask = np.pad(np.reshape(bmu, 1), np.array([[0, 1]]),'constant')
bmu_loc=np.reshape(index_map[bmu],2)
print(bmu_loc)

[0 2]


###  Calculate learning rate and radius

In [315]:

decay_function = np.subtract(1.0, np.divide(epoca_actual, epocas))
#print(decay_function)
aprendizaje_actual = np.multiply(i_aprendizaje, decay_function)
print(aprendizaje_actual)
radio_actual = np.multiply(radio, decay_function)

0.425


###   Adaptar la velocidad de aprendizaje a cada neurona según la posición.

In [316]:
bmu_matriz = np.stack([bmu_loc for i in range(x*y)])
print(bmu_matriz)

[[0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]
 [0 2]]


### distancia de de la neurona ganadora hacia  la vecindad

In [317]:
bmu_distance = np.sum(np.power(np.subtract(index_map, bmu_matriz), 2), 1)
print(bmu_distance)

func_vecindad =np.exp(np.negative(np.divide(np.array(bmu_distance, dtype= np.float32), np.array(np.power(radio,2),dtype = np.float32))))
print(func_vecindad)


[4 1 0 5 2 1 8 5 4]
[1.8315639e-02 3.6787945e-01 1.0000000e+00 6.7379470e-03 1.3533528e-01
 3.6787945e-01 3.3546262e-04 6.7379470e-03 1.8315639e-02]


### Matriz de aprendizaje

In [318]:
matriz_aprendizaje = np.multiply(aprendizaje_actual, func_vecindad)
print (matriz_aprendizaje)
 

[7.7841468e-03 1.5634876e-01 4.2500001e-01 2.8636276e-03 5.7517495e-02
 1.5634876e-01 1.4257162e-04 2.8636276e-03 7.7841468e-03]


### Actualizacion de pesos

In [319]:
multiplicador=np.stack([np.tile(matriz_aprendizaje[j],v_dim)for i in range(x*y)])
print (caf)

[[0.15634876 0.15634876 0.15634876 0.15634876 0.15634876 0.15634876
  0.15634876 0.15634876]
 [0.15634876 0.15634876 0.15634876 0.15634876 0.15634876 0.15634876
  0.15634876 0.15634876]
 [0.15634876 0.15634876 0.15634876 0.15634876 0.15634876 0.15634876
  0.15634876 0.15634876]
 [0.15634876 0.15634876 0.15634876 0.15634876 0.15634876 0.15634876
  0.15634876 0.15634876]
 [0.15634876 0.15634876 0.15634876 0.15634876 0.15634876 0.15634876
  0.15634876 0.15634876]
 [0.15634876 0.15634876 0.15634876 0.15634876 0.15634876 0.15634876
  0.15634876 0.15634876]
 [0.15634876 0.15634876 0.15634876 0.15634876 0.15634876 0.15634876
  0.15634876 0.15634876]
 [0.15634876 0.15634876 0.15634876 0.15634876 0.15634876 0.15634876
  0.15634876 0.15634876]
 [0.15634876 0.15634876 0.15634876 0.15634876 0.15634876 0.15634876
  0.15634876 0.15634876]]


In [320]:
delta = np.multiply(multiplicador,np.subtract(np.stack([v_entrada for i in range(x*y)]), m_pesos))   
print (delta)

[[0.58128701 1.26129967 0.28964028 0.16167366 1.1715902  1.01432782
  1.17789978 0.98993112]
 [0.62806672 1.0182609  0.36021911 0.00181658 1.01620144 0.9627069
  0.94471795 1.13350884]
 [0.653946   0.85298071 0.02897922 0.36217024 1.02949917 1.06841181
  1.11927795 0.90960573]
 [0.55148456 1.10487365 0.19053657 0.0661524  0.90772687 1.03856295
  1.26182536 1.22612681]
 [0.55250738 1.10442406 0.34343276 0.26956562 1.20793321 1.16337254
  0.87001851 0.86347638]
 [0.49103494 0.97914605 0.10805413 0.31223351 1.20771474 1.11125361
  1.03850917 1.22335992]
 [0.51693248 1.17671697 0.02824938 0.30979361 1.06556762 1.07062389
  0.87791836 0.8864493 ]
 [0.51748137 0.87852457 0.41362928 0.11006873 1.26666853 1.04762504
  0.97658027 0.9037932 ]
 [0.4377897  1.20595527 0.32089552 0.08195639 0.93804263 1.02444587
  1.10434072 0.91707506]]


In [325]:
new_pesos = np.add(m_pesos, delta)
print(new_pesos)
print("---------------------------------------------------")
m_pesos= new_pesos
print(m_pesos)

[[1.79483992 2.5548355  0.89777404 0.94293872 2.58649766 2.64200201
  2.58427075 2.65061261]
 [1.77832943 2.64061387 0.87286387 0.99935885 2.64134073 2.66022116
  2.6665702  2.59993813]
 [1.76919557 2.69894804 0.98977204 0.87217523 2.63664742 2.62291355
  2.6049608  2.67896274]
 [1.80535843 2.61004467 0.93275181 0.9766521  2.67962587 2.63344844
  2.55464996 2.56724944]
 [1.80499743 2.61020334 0.87878846 0.90485921 2.57367071 2.58939801
  2.6929347  2.69524369]
 [1.82669358 2.65441911 0.96186326 0.88979996 2.57374782 2.60779292
  2.63346742 2.56822599]
 [1.81755328 2.5846882  0.99002963 0.8906611  2.62391738 2.62213281
  2.69014652 2.6871356 ]
 [1.81735955 2.68993256 0.85401322 0.96115222 2.5529406  2.63025005
  2.65532467 2.68101422]
 [1.84548602 2.57436881 0.88674278 0.97107422 2.66892619 2.63843094
  2.61023276 2.67632651]]
---------------------------------------------------
[[1.79483992 2.5548355  0.89777404 0.94293872 2.58649766 2.64200201
  2.58427075 2.65061261]
 [1.77832943 2.64

In [322]:
centroid_matrix = [[] for i in range(x)]
#print(centroid_matrix)
for i, loc in enumerate(index_map):
            centroid_matrix[loc[0]].append(new_pesos[i])
            #print(centroid_matrix)

[[], [], []]
[[array([1.21355291, 1.29353583, 0.60813375, 0.78126506, 1.41490746,
       1.6276742 , 1.40637097, 1.66068149])], [], []]
[[array([1.21355291, 1.29353583, 0.60813375, 0.78126506, 1.41490746,
       1.6276742 , 1.40637097, 1.66068149]), array([1.15026271, 1.62235297, 0.51264476, 0.99754227, 1.62513929,
       1.69751426, 1.72185224, 1.46642929])], [], []]
[[array([1.21355291, 1.29353583, 0.60813375, 0.78126506, 1.41490746,
       1.6276742 , 1.40637097, 1.66068149]), array([1.15026271, 1.62235297, 0.51264476, 0.99754227, 1.62513929,
       1.69751426, 1.72185224, 1.46642929]), array([1.11524958, 1.84596733, 0.96079282, 0.51000499, 1.60714825,
       1.55450174, 1.48568285, 1.76935701])], [], []]
[[array([1.21355291, 1.29353583, 0.60813375, 0.78126506, 1.41490746,
       1.6276742 , 1.40637097, 1.66068149]), array([1.15026271, 1.62235297, 0.51264476, 0.99754227, 1.62513929,
       1.69751426, 1.72185224, 1.46642929]), array([1.11524958, 1.84596733, 0.96079282, 0.51000499, 1