In [80]:
import numpy as np

In [98]:
class SOM(object):
    
    def __init__(self, x, y, v_dim, i_aprendizaje, radio, epocas, datos):
            
            
        #Inisializando Propiedades
        self._x = x
        self._y = y
        self.i_aprendizaje = float(i_aprendizaje)
        self._radio = float(radio)
        self._epocas = epocas
       
        
        
        
        def _iterador(x,y):
                for i in range(x):
                    for j in range(y):
                        yield np.array([i, j])
        index_map =np.array(list(_iterador(x, y)))     
                
        m_pesos = np.random.random((x*y,v_dim))
        for epoca_actual in range(self._epocas):
            #print(m_pesos)
            for v_entrada in datos:
                m_entrada=np.stack([v_entrada for i in range(x*y)])
                #print(m_entrada)
                raiz_distancias=np.sum(np.power(np.subtract(m_pesos, m_entrada),2),1)
                #print(raiz_distancias)
                bmu = np.argmin(raiz_distancias, 0)
                #print(bmu)
                bmu_loc=np.reshape(index_map[bmu],2)
                #print(bmu_loc)
                decay_function = np.subtract(1.0, np.divide(epoca_actual, self._epocas))
                #print(decay_function)
                aprendizaje_actual = np.multiply(i_aprendizaje, decay_function)
                #print(aprendizaje_actual)
                radio_actual = np.multiply(radio, decay_function)
                bmu_matriz = np.stack([bmu_loc for i in range(x*y)])
                #print(bmu_matriz)
                bmu_distance = np.sum(np.power(np.subtract(index_map, bmu_matriz), 2), 1)
                #print(bmu_distance)
                func_vecindad =np.exp(np.negative(np.divide(np.array(bmu_distance, dtype= np.float32), np.array(np.power(radio,2),dtype = np.float32))))
                #print(func_vecindad)
                matriz_aprendizaje = np.multiply(aprendizaje_actual, func_vecindad)
                #print(matriz_aprendizaje)
                multiplicador=np.stack([np.tile(matriz_aprendizaje[i],v_dim)for i in range(x*y)])
                delta = np.multiply(multiplicador,np.subtract(np.stack([v_entrada for i in range(x*y)]), m_pesos))   
                #print (delta)
                new_pesos = np.add(m_pesos, delta)
                m_pesos= new_pesos
                #print(m_pesos)
                if (epoca_actual== epocas-1):
                    print("-------")
                    print("El vector ",v_entrada," esta clasificado en el grupo: ",bmu_loc[0])
                    #print(bmu_loc)
                
                
        centroid_matrix = [[] for i in range(x)]
        for i, loc in enumerate(index_map):
            centroid_matrix[loc[0]].append(new_pesos[i])
        print(centroid_matrix)
                
                
    

In [99]:
datos = [[2, 3, 1, 1, 3, 3, 3, 3], 
         [3, 2, 1, 0, 3, 3, 3, 3], 
         [2, 3, 1, 1, 2, 3, 3, 3],
         [2, 3, 1, 1, 2, 2, 3, 3],
         [2, 3, 1, 1, 1, 2, 3, 3],
         [1, 3, 1, 1, 2, 2, 3, 3], 
         [2, 1, 0, 0, 2, 2, 3, 3],
         [2, 1, 0, 0, 3, 2, 3, 3], 
         [1, 1, 0, 0, 2, 1, 3, 3], 
         [1, 1, 0, 0, 2, 1, 3, 3], 
         [1, 1, 0, 0, 1, 1, 3, 3],
         [1, 1, 0, 0, 0, 0, 3, 3], 
         [1, 1, 0, 0, 1, 1, 3, 3], 
         [3, 3, 1, 1, 4, 4, 2, 3], 
         [3, 3, 1, 1, 4, 4, 2, 3], 
         [3, 3, 1, 1, 4, 4, 3, 2], 
         [3, 3, 1, 1, 4, 4, 1, 2], 
         [3, 3, 1, 1, 3, 3, 1, 2], 
         [3, 3, 1, 1, 4, 4, 1, 2], 
         [3, 3, 1, 1, 3, 3, 1, 2], 
         [3, 3, 1, 1, 4, 3, 1, 2], 
         [3, 2, 1, 1, 3, 3, 1, 2], 
         [3, 3, 1, 1, 3, 2, 1, 1], 
         [3, 3, 1, 1, 3, 2, 1, 1], 
         [3, 2, 1, 1, 3, 4, 1, 1], 
         [3, 2, 1, 1, 3, 4, 1, 1], 
         [3, 2, 1, 1, 3, 3, 2, 2], 
         [2, 1, 1, 1, 4, 4, 1, 1], 
         [0, 4, 1, 0, 3, 3, 3, 3], 
         [0, 4, 1, 0, 3, 3, 3, 3], 
         [0, 4, 0, 0, 3, 3, 3, 3], 
         [0, 4, 0, 0, 3, 3, 3, 3]]

In [ ]:
som = SOM(3, 3,8, 0.5,  1.0, 10000, datos)


###    inicializando los pesos

In [84]:
x=3
y=3
v_entrada = [2, 3, 1, 1, 3, 3, 3, 3]
i_aprendizaje = 0.5
epoca_actual = 15
epocas = 100
radio_actual = 0.5
radio = 1
v_dim=8
#-------
m_pesos = np.random.random((x*y,v_dim))
print (m_pesos)
#creando el mapa de indices 
index_map =np.array(list(iterador(x, y)))

def iterador(x,y):
        for i in range(x):
            for j in range(y):
                yield np.array([i, j])

print (index_map)

#matriz de entrada
m_entrada=np.stack([v_entrada for i in range(x*y)])
print (m_entrada)
bmu_loc=np.reshape(index_map[bmu],2)
print(bmu_loc)



[[0.53384905 0.34646196 0.14716041 0.35167936 0.02380812 0.27209299
  0.33745381 0.19215098]
 [0.17653071 0.12777728 0.83045796 0.53353871 0.62779297 0.92668098
  0.65337515 0.19644732]
 [0.60634112 0.04682599 0.89646228 0.3901364  0.43222026 0.27138375
  0.46387421 0.6770201 ]
 [0.75074937 0.60715478 0.13164687 0.23399198 0.48883081 0.46192825
  0.91764796 0.79473461]
 [0.06215775 0.32753723 0.29968338 0.4965851  0.37321442 0.0879877
  0.04388989 0.90725875]
 [0.91582115 0.14148921 0.95593326 0.10000859 0.03508225 0.81220456
  0.23722759 0.91272963]
 [0.76615889 0.43108273 0.03887933 0.03803193 0.32780303 0.69313128
  0.5917075  0.32774192]
 [0.94702804 0.16798928 0.04418068 0.6925326  0.12610928 0.68495976
  0.96383168 0.57446027]
 [0.76340251 0.40403097 0.63754519 0.59646257 0.30527316 0.99134638
  0.76117345 0.9412846 ]]
[[0 0]
 [0 1]
 [0 2]
 [1 0]
 [1 1]
 [1 2]
 [2 0]
 [2 1]
 [2 2]]
[[2 3 1 1 3 3 3 3]
 [2 3 1 1 3 3 3 3]
 [2 3 1 1 3 3 3 3]
 [2 3 1 1 3 3 3 3]
 [2 3 1 1 3 3 3 3]
 [2 

### Calcular distancias

In [85]:
raiz_distancias=np.sum(np.power(np.subtract(m_pesos, m_entrada),2),1)
print(raiz_distancias)


[41.6108809  35.11360803 36.91318458 30.57430514 40.13913083 35.72524929
 35.3739513  33.785045   29.10934006]


###  indice de la neurona ganadora

In [86]:
bmu = np.argmin(raiz_distancias, 0)
#print (bmu)
#mask = np.pad(np.reshape(bmu, 1), np.array([[0, 1]]),'constant')
bmu_loc=np.reshape(index_map[bmu],2)
print(bmu_loc)

[2 2]


###  Calculate learning rate and radius

In [87]:

decay_function = np.subtract(1.0, np.divide(epoca_actual, epocas))
#print(decay_function)
aprendizaje_actual = np.multiply(i_aprendizaje, decay_function)
print(aprendizaje_actual)
radio_actual = np.multiply(radio, decay_function)

0.425


###   Adaptar la velocidad de aprendizaje a cada neurona según la posición.

In [88]:
bmu_matriz = np.stack([bmu_loc for i in range(x*y)])
print(bmu_matriz)

[[2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]]


### distancia de de la neurona ganadora hacia  la vecindad

In [89]:
bmu_distance = np.sum(np.power(np.subtract(index_map, bmu_matriz), 2), 1)
print(bmu_distance)

func_vecindad =np.exp(np.negative(np.divide(np.array(bmu_distance, dtype= np.float32), np.array(np.power(radio,2),dtype = np.float32))))
print(func_vecindad)


[8 5 4 5 2 1 4 1 0]
[3.3546262e-04 6.7379470e-03 1.8315639e-02 6.7379470e-03 1.3533528e-01
 3.6787945e-01 1.8315639e-02 3.6787945e-01 1.0000000e+00]


### Matriz de aprendizaje

In [90]:
matriz_aprendizaje = np.multiply(aprendizaje_actual, func_vecindad)
print (matriz_aprendizaje)
 

[1.4257162e-04 2.8636276e-03 7.7841468e-03 2.8636276e-03 5.7517495e-02
 1.5634876e-01 7.7841468e-03 1.5634876e-01 4.2500001e-01]


### Actualizacion de pesos

In [93]:
multiplicador=np.stack([np.tile(matriz_aprendizaje[i],v_dim)for i in range(x*y)])
print (multiplicador)

[[1.4257162e-04 1.4257162e-04 1.4257162e-04 1.4257162e-04 1.4257162e-04
  1.4257162e-04 1.4257162e-04 1.4257162e-04]
 [2.8636276e-03 2.8636276e-03 2.8636276e-03 2.8636276e-03 2.8636276e-03
  2.8636276e-03 2.8636276e-03 2.8636276e-03]
 [7.7841468e-03 7.7841468e-03 7.7841468e-03 7.7841468e-03 7.7841468e-03
  7.7841468e-03 7.7841468e-03 7.7841468e-03]
 [2.8636276e-03 2.8636276e-03 2.8636276e-03 2.8636276e-03 2.8636276e-03
  2.8636276e-03 2.8636276e-03 2.8636276e-03]
 [5.7517495e-02 5.7517495e-02 5.7517495e-02 5.7517495e-02 5.7517495e-02
  5.7517495e-02 5.7517495e-02 5.7517495e-02]
 [1.5634876e-01 1.5634876e-01 1.5634876e-01 1.5634876e-01 1.5634876e-01
  1.5634876e-01 1.5634876e-01 1.5634876e-01]
 [7.7841468e-03 7.7841468e-03 7.7841468e-03 7.7841468e-03 7.7841468e-03
  7.7841468e-03 7.7841468e-03 7.7841468e-03]
 [1.5634876e-01 1.5634876e-01 1.5634876e-01 1.5634876e-01 1.5634876e-01
  1.5634876e-01 1.5634876e-01 1.5634876e-01]
 [4.2500001e-01 4.2500001e-01 4.2500001e-01 4.2500001e-01 4.2500

In [94]:
delta = np.multiply(multiplicador,np.subtract(np.stack([v_entrada for i in range(x*y)]), m_pesos))   
print (delta)

[[2.09031514e-04 3.78319212e-04 1.21590720e-04 9.24321230e-05
  4.24320492e-04 3.88922117e-04 3.79603519e-04 4.00319579e-04]
 [5.22173703e-03 8.22497634e-03 4.85505269e-04 1.33577143e-03
  6.79311760e-03 5.93721363e-03 6.71985974e-03 8.02833090e-03]
 [1.08484453e-02 2.29879401e-02 8.05952847e-04 4.74726781e-03
  1.99879745e-02 2.12399495e-02 1.97415755e-02 1.80824166e-02]
 [3.57738860e-03 6.85221767e-03 2.48664001e-03 2.19356173e-03
  7.19105347e-03 7.26809237e-03 5.96308082e-03 6.31505888e-03]
 [1.11459832e-01 1.53713364e-01 4.02804574e-02 2.89551643e-02
  1.51086126e-01 1.67491653e-01 1.70028049e-01 1.20369234e-01]
 [1.69510025e-01 4.46924632e-01 6.88978081e-03 1.40712545e-01
  4.63561228e-01 3.42059114e-01 4.31956054e-01 3.26342144e-01]
 [9.60440031e-03 1.99968292e-02 7.48150437e-03 7.48810068e-03
  2.08007735e-02 1.79570048e-02 1.87465024e-02 2.08012492e-02]
 [1.64630865e-01 4.42781378e-01 1.49441170e-01 4.80721485e-02
  4.49329265e-01 3.61953682e-01 3.18352402e-01 3.79230141e-01]


In [95]:
new_pesos = np.add(m_pesos, delta)
print(new_pesos)
print("---------------------------------------------------")
m_pesos= new_pesos
print(m_pesos)

[[0.53405808 0.34684028 0.147282   0.35177179 0.02423244 0.27248191
  0.33783341 0.1925513 ]
 [0.18175245 0.13600225 0.83094347 0.53487449 0.63458608 0.93261819
  0.66009501 0.20447565]
 [0.61718956 0.06981393 0.89726823 0.39488367 0.45220824 0.2926237
  0.48361578 0.69510252]
 [0.75432676 0.614007   0.13413351 0.23618554 0.49602186 0.46919634
  0.92361104 0.80104967]
 [0.17361758 0.48125059 0.33996384 0.52554026 0.52430055 0.25547935
  0.21391794 1.02762799]
 [1.08533117 0.58841384 0.96282304 0.24072114 0.49864348 1.15426368
  0.66918364 1.23907178]
 [0.77576329 0.45107956 0.04636084 0.04552003 0.3486038  0.71108829
  0.610454   0.34854317]
 [1.11165891 0.61077066 0.19362185 0.74060475 0.57543854 1.04691344
  1.28218408 0.95369041]
 [1.28895646 1.50731784 0.79158849 0.76796598 1.4505321  1.84502419
  1.71267476 1.81623867]]
---------------------------------------------------
[[0.53405808 0.34684028 0.147282   0.35177179 0.02423244 0.27248191
  0.33783341 0.1925513 ]
 [0.18175245 0.136

In [96]:
centroid_matrix = [[] for i in range(x)]
#print(centroid_matrix)
for i, loc in enumerate(index_map):
            centroid_matrix[loc[0]].append(new_pesos[i])
            #print(centroid_matrix)