In [284]:
import numpy as np

In [285]:
class SOM(object):
     def __init__(self, x, y, v_dim, i_aprendizaje, radio, epocas):
            
            
        #Inisializando Propiedades
        self._x = x
        self._y = y
        self.i_aprendizaje = float(i_aprendizaje)
        self._radio = float(radio)
        self._epocas = epocas
        
        
        m_pesos = np.random.random((x*y,v_dim))
        index_map =np.array(list(_iterador(x, y)))
        def _iterador(self, x, y):
            for i in range(x):
                for j in range(y):
                    yield np.array([i, j])
        

###    inicializando los pesos

In [286]:
x=3
y=3
v_entrada = [2, 3, 1, 1, 3, 3, 3, 3]
i_aprendizaje = 0.5
epoca_actual = 15
epocas = 100
radio_actual = 0.5
radio = 1
v_dim=8
#-------
m_pesos = np.random.random((x*y,v_dim))
print (m_pesos)
#creando el mapa de indices 
index_map =np.array(list(_iterador(x, y)))
def _iterador(x,y):
        for i in range(x):
            for j in range(y):
                yield np.array([i, j])

print (index_map)

#matriz de entrada
m_entrada=np.stack([v_entrada for i in range(x*y)])
print (m_entrada)



[[0.52905033 0.06908728 0.84223512 0.06053752 0.55076366 0.22399505
  0.6620124  0.16874544]
 [0.04087341 0.10330844 0.77313595 0.16112466 0.88801693 0.2126288
  0.8585502  0.4978183 ]
 [0.53554625 0.38758351 0.15688536 0.651482   0.47705702 0.86233764
  0.48426548 0.75980061]
 [0.78297345 0.89841401 0.54754145 0.71707262 0.94204262 0.80566046
  0.28936835 0.98893599]
 [0.99816186 0.00973038 0.180385   0.97775673 0.45887635 0.17310854
  0.9221956  0.63812051]
 [0.35570576 0.05440904 0.50441691 0.66995395 0.78476621 0.82550138
  0.73871    0.47012513]
 [0.47921137 0.58743909 0.5408798  0.12365876 0.84202482 0.91012565
  0.2403393  0.14696008]
 [0.75672587 0.06773795 0.82917761 0.47677556 0.35256443 0.30805595
  0.82479714 0.24842765]
 [0.03674237 0.12516902 0.90573017 0.56516002 0.1053698  0.87095571
  0.44179649 0.53499522]]
[[0 0]
 [0 1]
 [0 2]
 [1 0]
 [1 1]
 [1 2]
 [2 0]
 [2 1]
 [2 2]]
[[2 3 1 1 3 3 3 3]
 [2 3 1 1 3 3 3 3]
 [2 3 1 1 3 3 3 3]
 [2 3 1 1 3 3 3 3]
 [2 3 1 1 3 3 3 3]
 [2 

### Calcular distancias

In [287]:
raiz_distancias=np.sum(np.power(np.subtract(m_pesos, m_entrada),2),1)
print(raiz_distancias)


[38.84857235 36.06080934 32.08390695 26.62480092 34.96202619 32.88414699
 33.89200911 37.00497114 37.84937372]


###  indice de la neurona ganadora

In [288]:
bmu = np.argmin(raiz_distancias, 0)
#print (bmu)
#mask = np.pad(np.reshape(bmu, 1), np.array([[0, 1]]),'constant')
bmu_loc=np.reshape(index_map[bmu],2)
print(bmu_loc)

[1 0]


###  Calculate learning rate and radius

In [289]:

decay_function = np.subtract(1.0, np.divide(epoca_actual, epocas))
#print(decay_function)
aprendizaje_actual = np.multiply(i_aprendizaje, decay_function)
print(aprendizaje_actual)
radio_actual = np.multiply(radio, decay_function)

0.425


###   Adaptar la velocidad de aprendizaje a cada neurona según la posición.

In [290]:
bmu_matriz = np.stack([bmu_loc for i in range(x*y)])
print(bmu_matriz)

[[1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]]


### distancia de de la neurona ganadora hacia  la vecindad

In [291]:
bmu_distance = np.sum(np.power(np.subtract(index_map, bmu_matriz), 2), 1)
print(bmu_distance)

func_vecindad =np.exp(np.negative(np.divide(np.array(bmu_distance, dtype= np.float32), np.array(np.power(radio,2),dtype = np.float32))))
print(func_vecindad)


[1 2 5 0 1 4 1 2 5]
[0.36787945 0.13533528 0.00673795 1.         0.36787945 0.01831564
 0.36787945 0.13533528 0.00673795]


### Matriz de aprendizaje

In [292]:
matriz_aprendizaje = np.multiply(aprendizaje_actual, func_vecindad)
print (matriz_aprendizaje)
 

[0.15634876 0.0575175  0.00286363 0.425      0.15634876 0.00778415
 0.15634876 0.0575175  0.00286363]


### Actualizacion de pesos

In [293]:
multiplicador=np.stack([np.tile(matriz_aprendizaje[j],v_dim)for i in range(x*y)])
print (caf)

[[0.15634876 0.15634876 0.15634876 0.15634876 0.15634876 0.15634876
  0.15634876 0.15634876]
 [0.15634876 0.15634876 0.15634876 0.15634876 0.15634876 0.15634876
  0.15634876 0.15634876]
 [0.15634876 0.15634876 0.15634876 0.15634876 0.15634876 0.15634876
  0.15634876 0.15634876]
 [0.15634876 0.15634876 0.15634876 0.15634876 0.15634876 0.15634876
  0.15634876 0.15634876]
 [0.15634876 0.15634876 0.15634876 0.15634876 0.15634876 0.15634876
  0.15634876 0.15634876]
 [0.15634876 0.15634876 0.15634876 0.15634876 0.15634876 0.15634876
  0.15634876 0.15634876]
 [0.15634876 0.15634876 0.15634876 0.15634876 0.15634876 0.15634876
  0.15634876 0.15634876]
 [0.15634876 0.15634876 0.15634876 0.15634876 0.15634876 0.15634876
  0.15634876 0.15634876]
 [0.15634876 0.15634876 0.15634876 0.15634876 0.15634876 0.15634876
  0.15634876 0.15634876]]


In [294]:
delta = np.multiply(multiplicador,np.subtract(np.stack([v_entrada for i in range(x*y)]), m_pesos))   
print (delta)

[[4.21225212e-03 8.39304265e-03 4.51779871e-04 2.69027072e-03
  7.01370084e-03 7.94944447e-03 6.69512587e-03 8.10765877e-03]
 [5.61020903e-03 8.29504598e-03 6.49654175e-04 2.40222658e-03
  6.04793306e-03 7.98199318e-03 6.13231481e-03 7.16531664e-03]
 [4.19365023e-03 7.48098803e-03 2.41436637e-03 9.98025772e-04
  7.22476921e-03 6.12146899e-03 7.20412688e-03 6.41509687e-03]
 [3.48511086e-03 6.01815969e-03 1.29567279e-03 8.10198653e-04
  5.89322361e-03 6.28377134e-03 7.76223966e-03 5.75893846e-03]
 [2.86889137e-03 8.56301868e-03 2.34707217e-03 6.36964532e-05
  7.27683189e-03 8.09516449e-03 5.95005809e-03 6.76354336e-03]
 [4.70864642e-03 8.43507565e-03 1.41916542e-03 9.45128985e-04
  6.34360468e-03 6.22695433e-03 6.47549252e-03 7.24461957e-03]
 [4.35497234e-03 6.90867608e-03 1.31474928e-03 2.50951498e-03
  6.17963733e-03 5.98462191e-03 7.90264061e-03 8.17004392e-03]
 [3.56027414e-03 8.39690661e-03 4.89171713e-04 1.49831995e-03
  7.58126964e-03 7.70872534e-03 6.22897101e-03 7.87947860e-03]


In [295]:
new_pesos = np.add(m_pesos, delta)
print(new_pesos)

[[0.53326258 0.07748032 0.8426869  0.06322779 0.55777736 0.23194449
  0.66870753 0.1768531 ]
 [0.04648362 0.11160349 0.7737856  0.16352689 0.89406486 0.22061079
  0.86468251 0.50498362]
 [0.5397399  0.3950645  0.15929973 0.65248003 0.48428179 0.86845911
  0.4914696  0.7662157 ]
 [0.78645856 0.90443217 0.54883713 0.71788282 0.94793584 0.81194423
  0.29713059 0.99469493]
 [1.00103075 0.0182934  0.18273207 0.97782042 0.46615318 0.1812037
  0.92814565 0.64488405]
 [0.3604144  0.06284412 0.50583608 0.67089908 0.79110981 0.83172833
  0.74518549 0.47736975]
 [0.48356634 0.59434776 0.54219455 0.12616828 0.84820446 0.91611027
  0.24824194 0.15513013]
 [0.76028615 0.07613486 0.82966678 0.47827388 0.3601457  0.31576468
  0.83102611 0.25630713]
 [0.04236441 0.13340147 0.90600013 0.56640524 0.11365894 0.8770525
  0.44912223 0.54205407]]


In [296]:
centroid_matrix = [[] for i in range(x)]
print(centroid_matrix)
for i, loc in enumerate(index_map):
            centroid_matrix[loc[0]].append(new_pesos[i])
            print(centroid_matrix)

[[], [], []]
[[array([0.53326258, 0.07748032, 0.8426869 , 0.06322779, 0.55777736,
       0.23194449, 0.66870753, 0.1768531 ])], [], []]
[[array([0.53326258, 0.07748032, 0.8426869 , 0.06322779, 0.55777736,
       0.23194449, 0.66870753, 0.1768531 ]), array([0.04648362, 0.11160349, 0.7737856 , 0.16352689, 0.89406486,
       0.22061079, 0.86468251, 0.50498362])], [], []]
[[array([0.53326258, 0.07748032, 0.8426869 , 0.06322779, 0.55777736,
       0.23194449, 0.66870753, 0.1768531 ]), array([0.04648362, 0.11160349, 0.7737856 , 0.16352689, 0.89406486,
       0.22061079, 0.86468251, 0.50498362]), array([0.5397399 , 0.3950645 , 0.15929973, 0.65248003, 0.48428179,
       0.86845911, 0.4914696 , 0.7662157 ])], [], []]
[[array([0.53326258, 0.07748032, 0.8426869 , 0.06322779, 0.55777736,
       0.23194449, 0.66870753, 0.1768531 ]), array([0.04648362, 0.11160349, 0.7737856 , 0.16352689, 0.89406486,
       0.22061079, 0.86468251, 0.50498362]), array([0.5397399 , 0.3950645 , 0.15929973, 0.65248003, 0